name: Update S3

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

# Set necessary permissions for the workflow
permissions:
  contents: read
  id-token: write  # Needed for OIDC token

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::696816923853:role/Full-github-Full-S3 # ARN of IAM role it is assuming
          aws-region: us-east-1

      # Step 3: Sync files to the S3 bucket
      - name: Sync files to S3
        run: aws s3 sync . s3://scottspicer24-portfolio-website --exclude ".git/*" --exclude ".github/*" --exclude "README.md" --exclude "*.mp4" --exclude ".vscode/*" --exclude "__pycache__/*"

